name: Sanjay's Blog
description: Blogging about stuffs
meta_description: "Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://sanzay.me'
google_analytics: 'G-WRQ23KBKSJ'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Sanjay Pandey'
